# Generated by Django 5.1.7 on 2025-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('operator', 'Operator')], default='operator', max_length=8),
        ),
    ]
