# Generated by Django 5.1.7 on 2025-05-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
