# Generated by Django 5.1.7 on 2025-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
