# Generated by Django 5.1.7 on 2025-05-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories_service', '0002_alter_accessories_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessories',
            new_name='Accessory',
        ),
    ]
