# Generated by Django 5.1.7 on 2025-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumables',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
