# Generated by Django 5.1.7 on 2025-05-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumables_service', '0002_alter_consumables_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consumables',
            new_name='Consumable',
        ),
    ]
