# Generated by Django 5.1.7 on 2025-05-04 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order_number', models.CharField(blank=True, max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('model_number', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('minimum_quantity', models.IntegerField(blank=True, null=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField()),
                ('manufacturer_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='consumable_images/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='consumables_ms.consumable')),
            ],
        ),
    ]
