# Generated by Django 5.2.1 on 2025-09-17 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables_ms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
