# Generated by Django 5.1.7 on 2025-05-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumables_ms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumableImages',
            new_name='ConsumableImage',
        ),
    ]
