# Generated by Django 5.2.4 on 2025-11-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts_ms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='URL',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asset_checkout',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
