# Generated by Django 5.2.1 on 2025-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts_ms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='zip',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
