# Generated by Django 5.1.7 on 2025-11-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts_ms', '0002_rename_url_supplier_url_supplier_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='pasig', max_length=50),
            preserve_default=False,
        ),
    ]
