# Generated by Django 5.2.4 on 2025-11-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts_ms', '0002_rename_url_supplier_url_alter_ticket_asset_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state_province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('checkout', 'Checkout'), ('checkin', 'Checkin')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
