# Generated by Django 5.1.7 on 2025-11-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts_ms', '0003_alter_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='category',
            field=models.CharField(choices=[('asset', 'Asset Status'), ('repair', 'Repair Status')], default='asset', max_length=10),
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(blank=True, choices=[('deployable', 'Deployable'), ('deployed', 'Deployed'), ('undeployable', 'Undeployable'), ('pending', 'Pending'), ('archived', 'Archived')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.PositiveIntegerField(),
        ),
    ]
