# Generated by Django 5.1.7 on 2025-12-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts_ms', '0003_supplier_country_supplier_fax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='category',
            field=models.CharField(choices=[('asset', 'Asset Status'), ('repair', 'Repair Status')], default='asset', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='asset_checkin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(blank=True, choices=[('deployable', 'Deployable'), ('deployed', 'Deployed'), ('undeployable', 'Undeployable'), ('pending', 'Pending'), ('archived', 'Archived')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='employee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.PositiveIntegerField(),
        ),
    ]
