# Generated by Django 5.1.7 on 2025-11-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts_ms', '0005_employee_alter_ticket_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asset_checkin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
