# Generated by Django 5.1.7 on 2025-12-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts_ms', '0006_ticket_asset_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manu_url',
            new_name='website_url',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='support_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
