# Generated by Django 5.1.7 on 2026-01-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contexts_ms', '0002_employee_rename_manu_url_manufacturer_website_url_and_more'),
        ('contexts_ms', '0007_rename_manu_url_manufacturer_website_url_and_more'),
    ]

    operations = [
    ]
