# Generated by Django merge migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contexts_ms', '0005_rename_manu_url_manufacturer_website_url_and_more'),
        ('contexts_ms', '0007_rename_manu_url_manufacturer_website_url_and_more'),
    ]

    operations = [
    ]

