# Generated by Django 5.1.7 on 2025-10-24 06:19

import assets_ms.models
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20, unique=True)),
                ('status', models.PositiveIntegerField()),
                ('supplier', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='asset_images/', validators=[assets_ms.models.validate_image])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('audit_date', models.DateField(default=django.utils.timezone.now)),
                ('next_audit_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.PositiveIntegerField()),
                ('manufacturer', models.IntegerField(blank=True, null=True)),
                ('supplier', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.PositiveIntegerField(blank=True, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('order_number', models.CharField(blank=True, max_length=30, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('minimum_quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='component_images/', validators=[assets_ms.models.validate_image])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.PositiveIntegerField()),
                ('manufacturer', models.PositiveIntegerField(blank=True, null=True)),
                ('depreciation', models.PositiveIntegerField(blank=True, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('end_of_life', models.DateField(blank=True, null=True)),
                ('default_purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', validators=[assets_ms.models.validate_image])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssetCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_to', models.PositiveIntegerField()),
                ('location', models.CharField()),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
                ('condition', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='asset_checkout_images/', validators=[assets_ms.models.validate_image])),
                ('asset', models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, related_name='asset_checkouts', to='assets_ms.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(auto_now_add=True)),
                ('condition', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='asset_checkin_images/', validators=[assets_ms.models.validate_image])),
                ('asset_checkout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_checkin', to='assets_ms.assetcheckout')),
            ],
        ),
        migrations.CreateModel(
            name='AuditFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audit_files/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assets_ms.audit')),
            ],
        ),
        migrations.CreateModel(
            name='AuditSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 10, 24, 6, 19, 31, 446464, tzinfo=datetime.timezone.utc), editable=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='assets_ms.asset')),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_audit', to='assets_ms.auditschedule'),
        ),
        migrations.CreateModel(
            name='ComponentCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_to', to='assets_ms.asset')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_checkouts', to='assets_ms.component')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('component_checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_checkins', to='assets_ms.componentcheckout')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, related_name='product_assets', to='assets_ms.product'),
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Repair'), ('upgrade', 'Upgrade'), ('test', 'Test'), ('hardware', 'Hardware'), ('software', 'Software')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status_id', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_assets', to='assets_ms.asset')),
            ],
        ),
        migrations.CreateModel(
            name='RepairFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='repair_files/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assets_ms.repair')),
            ],
        ),
    ]
