# Generated by Django 5.1.7 on 2025-05-05 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier_id',
            new_name='default_supplier_id',
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
