# Generated by Django 5.2 on 2025-05-18 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 12, 9, 6, 430992, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AddField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 12, 9, 6, 430604, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='audit',
            name='audit_date',
            field=models.DateField(default=datetime.date(2025, 5, 18)),
        ),
        migrations.AlterField(
            model_name='audit',
            name='next_audit_date',
            field=models.DateField(default=datetime.date(2025, 5, 18)),
        ),
    ]
