# Generated by Django 5.1.7 on 2025-09-26 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 26, 9, 46, 48, 709653, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 26, 9, 46, 48, 709278, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
