# Generated by Django 5.1.7 on 2025-09-15 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 9, 42, 24, 405625, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 9, 42, 24, 405297, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
