# Generated by Django 5.1.7 on 2025-09-26 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0002_alter_audit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 26, 9, 47, 2, 523403, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 26, 9, 47, 2, 523086, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
