# Generated by Django 5.2 on 2025-05-05 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0002_rename_supplier_id_product_default_supplier_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
