# Generated by Django 5.1.7 on 2025-11-29 02:06

import assets_ms.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0002_remove_audit_next_audit_date_assetcheckin_ticket_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcheckin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='image',
        ),
        migrations.AddField(
            model_name='assetcheckin',
            name='location',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcheckin',
            name='status',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 2, 6, 34, 839574, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.CreateModel(
            name='AssetCheckinFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='asset_checkin_files/', validators=[assets_ms.models.validate_file])),
                ('is_deleted', models.BooleanField(default=False)),
                ('asset_checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assets_ms.assetcheckin')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCheckoutFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='asset_checkout_files/', validators=[assets_ms.models.validate_file])),
                ('is_deleted', models.BooleanField(default=False)),
                ('asset_checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assets_ms.assetcheckout')),
            ],
        ),
    ]
