# Generated by Django 5.2.4 on 2025-12-01 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0003_remove_assetcheckin_image_remove_assetcheckout_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 10, 11, 9, 244778, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
