# Generated by Django 5.2 on 2025-05-06 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0003_alter_audit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 6)),
        ),
    ]
