# Generated by Django 5.1.7 on 2025-11-29 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0003_remove_assetcheckin_image_remove_assetcheckout_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcheckout',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='status',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetcheckout',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 3, 40, 6, 56410, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
