# Generated by Django 5.2 on 2025-05-06 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0004_alter_audit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='date',
            new_name='audit_date',
        ),
        migrations.AddField(
            model_name='audit',
            name='next_audit_date',
            field=models.DateField(default=datetime.date(2025, 5, 6)),
        ),
    ]
