# Generated by Django 5.1.7 on 2025-06-12 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0004_alter_audit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 21, 59, 43, 145776, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 21, 59, 43, 145255, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
