# Generated by Django 5.1.7 on 2025-11-29 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0004_assetcheckout_revenue_assetcheckout_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 16, 1, 34, 945240, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
