# Generated by Django 5.1.7 on 2025-06-14 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0005_alter_audit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_date',
            field=models.DateField(default=datetime.date(2025, 6, 14)),
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 17, 29, 22, 186435, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='audit',
            name='next_audit_date',
            field=models.DateField(default=datetime.date(2025, 6, 14)),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 17, 29, 22, 185779, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
