# Generated by Django 5.1.7 on 2025-06-17 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0005_alter_audit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='audit',
            name='audit_date',
            field=models.DateField(default=datetime.date(2025, 6, 17)),
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 16, 31, 32, 950405, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='audit',
            name='next_audit_date',
            field=models.DateField(default=datetime.date(2025, 6, 17)),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 16, 31, 32, 949696, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
