# Generated by Django 5.1.7 on 2025-11-29 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0006_alter_auditschedule_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 17, 3, 13, 283124, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
