# Generated by Django 5.2.4 on 2025-12-08 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0006_activitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='assets_ms_a_datetim_69017e_idx',
            old_name='assets_ms_a_datetim_e61a88_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='assets_ms_a_activit_5c652f_idx',
            old_name='assets_ms_a_activit_3c5c7a_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='assets_ms_a_action_075d7d_idx',
            old_name='assets_ms_a_action_8f3a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='assets_ms_a_user_id_fdfa2f_idx',
            old_name='assets_ms_a_user_id_7d2e4c_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='assets_ms_a_item_id_d0df13_idx',
            old_name='assets_ms_a_item_id_9a1f5d_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 8, 5, 30, 32, 868012, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
