# Generated by Django 5.1.7 on 2025-06-14 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0006_alter_audit_audit_date_alter_audit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='test_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 17, 41, 52, 314185, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 17, 41, 52, 313557, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
