# Generated by Django 5.1.7 on 2025-06-17 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0006_asset_test_alter_audit_audit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='test',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='asset',
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 16, 34, 30, 736506, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 16, 34, 30, 736125, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
