# Generated by Django 5.1.7 on 2025-06-17 16:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0007_remove_asset_test_remove_assetcheckout_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcheckout',
            name='asset',
            field=models.ForeignKey(default=24, limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, related_name='asset_checkouts', to='assets_ms.asset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 16, 35, 38, 758642, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 16, 35, 38, 758260, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
