# Generated by Django 5.2.4 on 2025-12-14 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0007_activitylog_user_id_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 6, 41, 14, 892109, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
