# Generated by Django 5.1.7 on 2025-06-14 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0007_asset_test_only_alter_audit_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='test_only',
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 17, 46, 2, 956980, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 17, 46, 2, 956407, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
