# Generated by Django 5.1.7 on 2025-11-29 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0007_alter_auditschedule_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcheckin',
            name='status',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='status',
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 20, 17, 2, 756236, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
