# Generated by Django 5.2.4 on 2025-12-14 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0008_alter_auditschedule_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivtyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('SCHEDULE', 'Schedule'), ('PERFORM', 'Perform')], max_length=15)),
                ('item_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('target_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 9, 1, 25, 775913, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
