# Generated by Django 5.1.7 on 2025-06-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0008_assetcheckout_asset_alter_audit_created_at_and_more'),
        ('assets_ms', '0008_remove_asset_test_only_alter_audit_created_at_and_more'),
    ]

    operations = [
    ]
