# Generated by Django 5.1.7 on 2025-06-19 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0009_merge_20250620_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcheckout',
            name='to_location',
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='test',
            field=models.CharField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audit',
            name='audit_date',
            field=models.DateField(default=datetime.date(2025, 6, 19)),
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 16, 59, 48, 738382, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='audit',
            name='next_audit_date',
            field=models.DateField(default=datetime.date(2025, 6, 19)),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 16, 59, 48, 737429, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
