# Generated by Django 5.2.4 on 2025-12-14 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0009_activtylog_delete_activitylog_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivtyLog',
            new_name='ActivityLog',
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 9, 15, 35, 475540, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
