# Generated by Django 5.1.7 on 2025-06-19 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0010_remove_assetcheckout_to_location_assetcheckout_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcheckout',
            old_name='test',
            new_name='to_location',
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 17, 3, 3, 181443, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 17, 3, 3, 180619, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
