# Generated by Django 5.1.7 on 2025-12-09 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0010_assetcheckin_created_at_assetcheckinfile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 9, 10, 56, 13, 260808, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
