# Generated by Django 5.2.4 on 2025-12-20 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0011_asset_created_at_asset_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 20, 4, 33, 10, 642778, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
