# Generated by Django 5.1.7 on 2025-06-19 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0011_rename_test_assetcheckout_to_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcheckout',
            name='checkout_date',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='confirmation_notes',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='image',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='to_user_id',
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 17, 5, 32, 192253, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 17, 5, 32, 191574, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
