# Generated by Django 5.1.7 on 2025-06-19 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0012_remove_assetcheckout_checkout_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcheckout',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='location',
            field=models.CharField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 17, 7, 39, 575091, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 17, 7, 39, 574591, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
