# Generated by Django 5.1.7 on 2025-12-19 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0012_activitylog_assetreporttemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 19, 13, 44, 37, 239764, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
