# Generated by Django 5.1.7 on 2025-06-19 18:00

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0013_assetcheckout_is_deleted_assetcheckout_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcheckout',
            name='checkout_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='condition',
            field=models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='confirmation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_checkout_images/'),
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='to_location',
            field=models.CharField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='to_user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 17, 59, 14, 991768, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 17, 59, 14, 990616, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
