# Generated by Django 5.2.1 on 2026-01-11 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0013_alter_auditschedule_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-datetime']},
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='module',
            new_name='activity_type',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='created_at',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='target_user_id',
            new_name='target_id',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='item_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 11, 21, 8, 14, 743227, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
