# Generated by Django 5.1.7 on 2025-06-20 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0014_assetcheckout_checkout_date_assetcheckout_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcheckin',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='assetcheckin',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='assetcheckin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='assetcheckin',
            name='location',
        ),
        migrations.RemoveField(
            model_name='assetcheckin',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assetcheckin',
            name='status',
        ),
        migrations.AlterField(
            model_name='audit',
            name='audit_date',
            field=models.DateField(default=datetime.date(2025, 6, 20)),
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 8, 30, 14, 463028, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='audit',
            name='next_audit_date',
            field=models.DateField(default=datetime.date(2025, 6, 20)),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 8, 30, 14, 462715, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
