# Generated by Django merge migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0002_remove_audit_next_audit_date_repair_supplier_id_and_more'),
        ('assets_ms', '0012_alter_auditschedule_created_at'),
        ('assets_ms', '0014_alter_activitylog_options_and_more'),
    ]

    operations = [
    ]

