# Generated by Django 5.1.7 on 2025-06-20 08:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0015_remove_assetcheckin_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcheckin',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcheckin',
            name='condition',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcheckin',
            name='image',
            field=models.ImageField(default='a', upload_to='asset_checkin_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcheckin',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 8, 36, 36, 755102, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 8, 36, 36, 754770, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
