# Generated by Django 5.1.7 on 2025-06-27 06:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0017_manufacturer_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 6, 58, 59, 926548, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 6, 58, 59, 926243, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets_ms.manufacturer'),
            preserve_default=False,
        ),
    ]
