# Generated by Django 5.1.7 on 2025-06-27 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0018_alter_audit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 19, 43, 56, 511571, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 19, 43, 56, 511145, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='manufacturer',
            field=models.IntegerField(),
        ),
    ]
