# Generated by Django 5.2.1 on 2025-09-17 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_ms', '0019_alter_audit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_date',
            field=models.DateField(default=datetime.date(2025, 9, 17)),
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 17, 14, 22, 39, 653376, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='audit',
            name='next_audit_date',
            field=models.DateField(default=datetime.date(2025, 9, 17)),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 17, 14, 22, 39, 653119, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
